model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 3072
  image_size: 448
  end_sym: "</s>"
  llama_model: "/fast/vfourel/LMMmodels/Llama-2-7b-chat-hf" 
  ckpt: '/fast/vfourel/LMMmodels/minigptv2CheckPoints/minigptv2_checkpoint.pth' 
  use_grad_checkpoint: True #06125
  use_grad_checkpoint_llm: False  # modify this to check if it changes the training  # make the difference between the two types of checkpoints. Only work if False,

  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  sharegpt_detail:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

  gpt4visionface_detail:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-7
  min_lr: 1e-8
  warmup_lr: 5e-8
  accum_grad_iters: 8 # VF: we need to add this to counter the low  batch and worker numbers

  weight_decay: 0.05
  max_epoch: 200
  num_workers: 1
  warmup_steps: 1000
  iters_per_epoch: 2500

  seed: 14401
  output_dir: '/fast/vfourel/faceGPTOutput' 

  amp: True
  resume_ckpt_path: null
  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_finetune