datasets:
  RealisticEmotions_detail:
    data_type: images
    build_info:
      image_path: /fast/vfourel/FaceGPT/Data/MiniFaceGPT4Data/RealisticEmotionsData/Images
      ann_path: /fast/vfourel/FaceGPT/Data/MiniFaceGPT4Data/RealisticEmotionsData/Annotations/Modified_PromptsSmall_AffectOnly_41ksamples.json